//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baballonia.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baballonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheek Expressions.
        /// </summary>
        public static string Calibration_Cheek_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Cheek_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Expressions.
        /// </summary>
        public static string Calibration_Eye_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents eyes from looking out in opposite directions, but may overcorrect..
        /// </summary>
        public static string Calibration_Eye_Expressions_Stabilize_Eyes_Description {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Stabilize_Eyes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilize Eyes.
        /// </summary>
        public static string Calibration_Eye_Expressions_Stabilize_Eyes_Header {
            get {
                return ResourceManager.GetString("Calibration_Eye_Expressions_Stabilize_Eyes_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Raising the.
        /// </summary>
        public static string Calibration_Instructions_Bullet1_1 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Bullet1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value requires a stronger expression before it starts to show..
        /// </summary>
        public static string Calibration_Instructions_Bullet1_2 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Bullet1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Lowering the.
        /// </summary>
        public static string Calibration_Instructions_Bullet2_1 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Bullet2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value means a smaller expression will reach 100% faster..
        /// </summary>
        public static string Calibration_Instructions_Bullet2_2 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Bullet2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The below sliders are used to calibrate the.
        /// </summary>
        public static string Calibration_Instructions_Line1 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of your face expressions..
        /// </summary>
        public static string Calibration_Instructions_Line1_2 {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Line1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string Calibration_Instructions_Maximum {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string Calibration_Instructions_Minimum {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sensitivity.
        /// </summary>
        public static string Calibration_Instructions_Sensitivity {
            get {
                return ResourceManager.GetString("Calibration_Instructions_Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaw Expressions.
        /// </summary>
        public static string Calibration_Jaw_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Jaw_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth Expressions.
        /// </summary>
        public static string Calibration_Mouth_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Mouth_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nose Expressions.
        /// </summary>
        public static string Calibration_Nose_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Nose_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Maximums.
        /// </summary>
        public static string Calibration_Reset_Maximums {
            get {
                return ResourceManager.GetString("Calibration_Reset_Maximums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Minimums.
        /// </summary>
        public static string Calibration_Reset_Minimums {
            get {
                return ResourceManager.GetString("Calibration_Reset_Minimums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string Calibration_Title_Header {
            get {
                return ResourceManager.GetString("Calibration_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tongue Expressions.
        /// </summary>
        public static string Calibration_Tongue_Expressions_Header {
            get {
                return ResourceManager.GetString("Calibration_Tongue_Expressions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing....
        /// </summary>
        public static string Common_Start_Typing {
            get {
                return ResourceManager.GetString("Common_Start_Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string DropOverlay_Dismiss_Button {
            get {
                return ResourceManager.GetString("DropOverlay_Dismiss_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this warning again.
        /// </summary>
        public static string DropOverlay_DontShowAgain {
            get {
                return ResourceManager.GetString("DropOverlay_DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important!.
        /// </summary>
        public static string DropOverlay_Important_Header {
            get {
                return ResourceManager.GetString("DropOverlay_Important_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer babble trackers have a 20 second delay after being plugged in before they can be used. It will make a USB plugging-in sound when it is ready!.
        /// </summary>
        public static string DropOverlay_Message {
            get {
                return ResourceManager.GetString("DropOverlay_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle wired/wireless mode.
        /// </summary>
        public static string Firmware_Device_Configuration_Description {
            get {
                return ResourceManager.GetString("Firmware_Device_Configuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Configuration.
        /// </summary>
        public static string Firmware_Device_Configuration_Header {
            get {
                return ResourceManager.GetString("Firmware_Device_Configuration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • After powering on/connecting your device you will have 20 seconds to press &quot;Refresh&quot; and select your device from the dropdown.
        /// </summary>
        public static string Firmware_Device_Instructions_1 {
            get {
                return ResourceManager.GetString("Firmware_Device_Instructions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Certain configuration operations will take a little bit!.
        /// </summary>
        public static string Firmware_Device_Instructions_2 {
            get {
                return ResourceManager.GetString("Firmware_Device_Instructions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle wired/wireless mode.
        /// </summary>
        public static string Firmware_Device_Mode_Header {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • You WILL need to restart your tracker after changing the mode.
        /// </summary>
        public static string Firmware_Device_Mode_Instruction_1 {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Instruction_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • You MAY need to restart the app after a flash for trackers to show.
        /// </summary>
        public static string Firmware_Device_Mode_Instruction_2 {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Instruction_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a mode....
        /// </summary>
        public static string Firmware_Device_Mode_Select_Placeholder {
            get {
                return ResourceManager.GetString("Firmware_Device_Mode_Select_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Firmware.
        /// </summary>
        public static string Firmware_Flashing_Button {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done! You will need to restart your tracker.
        /// </summary>
        public static string Firmware_Flashing_Complete {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash your device&apos;s firmware.
        /// </summary>
        public static string Firmware_Flashing_Description {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashing Options.
        /// </summary>
        public static string Firmware_Flashing_Header {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will take around ~10 seconds. Don&apos;t leave this page!.
        /// </summary>
        public static string Firmware_Flashing_Note {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUTION!! THIS WILL FACTORY RESET YOUR TRACKER. YOU WILL NEED TO PERFORM A FIRST TIME SET UP AFTER FLASHING YOUR TRACKER..
        /// </summary>
        public static string Firmware_Flashing_Warning {
            get {
                return ResourceManager.GetString("Firmware_Flashing_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Mode.
        /// </summary>
        public static string Firmware_ModeSetButton_Default {
            get {
                return ResourceManager.GetString("Firmware_ModeSetButton_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting mode.
        /// </summary>
        public static string Firmware_ModeSetButton_Setting {
            get {
                return ResourceManager.GetString("Firmware_ModeSetButton_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set!.
        /// </summary>
        public static string Firmware_ModeSetButton_Success {
            get {
                return ResourceManager.GetString("Firmware_ModeSetButton_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Devices.
        /// </summary>
        public static string Firmware_RefreshDevices_Default {
            get {
                return ResourceManager.GetString("Firmware_RefreshDevices_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} device(s)..
        /// </summary>
        public static string Firmware_RefreshDevices_Found {
            get {
                return ResourceManager.GetString("Firmware_RefreshDevices_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing.
        /// </summary>
        public static string Firmware_RefreshDevices_Refreshing {
            get {
                return ResourceManager.GetString("Firmware_RefreshDevices_Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your tracker.
        /// </summary>
        public static string Firmware_Select_Tracker_Header {
            get {
                return ResourceManager.GetString("Firmware_Select_Tracker_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker connected!.
        /// </summary>
        public static string Firmware_SelectTracker_Connected {
            get {
                return ResourceManager.GetString("Firmware_SelectTracker_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tracker.
        /// </summary>
        public static string Firmware_SelectTracker_Default {
            get {
                return ResourceManager.GetString("Firmware_SelectTracker_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tracker did not respond..
        /// </summary>
        public static string Firmware_SelectTracker_NoResponse {
            get {
                return ResourceManager.GetString("Firmware_SelectTracker_NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string Firmware_Title_Header {
            get {
                return ResourceManager.GetString("Firmware_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see trackers....
        /// </summary>
        public static string Firmware_TrackerComboBox_Default {
            get {
                return ResourceManager.GetString("Firmware_TrackerComboBox_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Wifi and more.
        /// </summary>
        public static string Firmware_Wifi_Configuration_Description {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Configuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi Configuration.
        /// </summary>
        public static string Firmware_Wifi_Configuration_Header {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Configuration_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your Wi-Fi credentials.
        /// </summary>
        public static string Firmware_Wifi_Credentials_Header {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Credentials_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • If you want to use your tracker wirelessly, you NEED to set its Wifi credentials.
        /// </summary>
        public static string Firmware_Wifi_Instructions_1 {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Instructions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • You MUST scan for Wifi networks BEFORE you can set your Wifi credentials.
        /// </summary>
        public static string Firmware_Wifi_Instructions_2 {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Instructions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi Password.
        /// </summary>
        public static string Firmware_Wifi_Password_Label {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter WiFi password....
        /// </summary>
        public static string Firmware_Wifi_Password_Placeholder {
            get {
                return ResourceManager.GetString("Firmware_Wifi_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi Network Name (SSID).
        /// </summary>
        public static string Firmware_Wifi_SSID_Label {
            get {
                return ResourceManager.GetString("Firmware_Wifi_SSID_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing to see WiFi networks....
        /// </summary>
        public static string Firmware_Wifi_SSID_Placeholder {
            get {
                return ResourceManager.GetString("Firmware_Wifi_SSID_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Wifi Networks.
        /// </summary>
        public static string Firmware_WifiScanButton_Default {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan failed. Click to try again..
        /// </summary>
        public static string Firmware_WifiScanButton_Error {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning. This will take at most 30 seconds.
        /// </summary>
        public static string Firmware_WifiScanButton_Scanning {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} networks. Click to scan again..
        /// </summary>
        public static string Firmware_WifiScanButton_Success {
            get {
                return ResourceManager.GetString("Firmware_WifiScanButton_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Wifi Creds.
        /// </summary>
        public static string Firmware_WifiSetButton_Default {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        public static string Firmware_WifiSetButton_Error {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting WiFi credentials.
        /// </summary>
        public static string Firmware_WifiSetButton_Setting {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent!.
        /// </summary>
        public static string Firmware_WifiSetButton_Success {
            get {
                return ResourceManager.GetString("Firmware_WifiSetButton_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust the brightness of the image.
        /// </summary>
        public static string Home_Cameras_Brightness_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Brightness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Brightness.
        /// </summary>
        public static string Home_Cameras_Brightness_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Brightness_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropping.
        /// </summary>
        public static string Home_Cameras_Cropping_Mode {
            get {
                return ResourceManager.GetString("Home_Cameras_Cropping_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip the image horizontally.
        /// </summary>
        public static string Home_Cameras_Horizontal_Flip_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Horizontal_Flip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal flip.
        /// </summary>
        public static string Home_Cameras_Horizontal_Flip_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Horizontal_Flip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates the image in a circle.
        /// </summary>
        public static string Home_Cameras_Rotation_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Rotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Rotation.
        /// </summary>
        public static string Home_Cameras_Rotation_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Rotation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Camera.
        /// </summary>
        public static string Home_Cameras_Start_Camera {
            get {
                return ResourceManager.GetString("Home_Cameras_Start_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Camera.
        /// </summary>
        public static string Home_Cameras_Stop_Camera {
            get {
                return ResourceManager.GetString("Home_Cameras_Stop_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Home_Cameras_Tracking_Mode {
            get {
                return ResourceManager.GetString("Home_Cameras_Tracking_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip the image vertically.
        /// </summary>
        public static string Home_Cameras_Vertical_Flip_Description {
            get {
                return ResourceManager.GetString("Home_Cameras_Vertical_Flip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Flip.
        /// </summary>
        public static string Home_Cameras_Vertical_Flip_Header {
            get {
                return ResourceManager.GetString("Home_Cameras_Vertical_Flip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye Calibration.
        /// </summary>
        public static string Home_Eye_Calibration {
            get {
                return ResourceManager.GetString("Home_Eye_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Camera Address.
        /// </summary>
        public static string Home_Face_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Camera.
        /// </summary>
        public static string Home_Face_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Face Frame.
        /// </summary>
        public static string Home_Face_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Camera Settings.
        /// </summary>
        public static string Home_Face_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Face_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Camera Address.
        /// </summary>
        public static string Home_Left_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Eye Camera.
        /// </summary>
        public static string Home_Left_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Left Frame.
        /// </summary>
        public static string Home_Left_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Camera Settings.
        /// </summary>
        public static string Home_Left_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Left_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Camera Address.
        /// </summary>
        public static string Home_Right_Camera_Address {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Eye Camera.
        /// </summary>
        public static string Home_Right_Camera_Header {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Right Frame.
        /// </summary>
        public static string Home_Right_Camera_Select_Entire_Frame {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Select_Entire_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Camera Settings.
        /// </summary>
        public static string Home_Right_Camera_Settings {
            get {
                return ResourceManager.GetString("Home_Right_Camera_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title_Header {
            get {
                return ResourceManager.GetString("Home_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need help putting your tracker together, here&apos;s a useful Youtube tutorial!.
        /// </summary>
        public static string Onboarding_Assembly_Description {
            get {
                return ResourceManager.GetString("Onboarding_Assembly_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemble Your Tracker.
        /// </summary>
        public static string Onboarding_Assembly_Header {
            get {
                return ResourceManager.GetString("Onboarding_Assembly_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re all set to start using the new Babble App!.
        /// </summary>
        public static string Onboarding_Complete_Description1 {
            get {
                return ResourceManager.GetString("Onboarding_Complete_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can revisit this page in the settings..
        /// </summary>
        public static string Onboarding_Complete_Description2 {
            get {
                return ResourceManager.GetString("Onboarding_Complete_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Complete!.
        /// </summary>
        public static string Onboarding_Complete_Header {
            get {
                return ResourceManager.GetString("Onboarding_Complete_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Onboarding_Skip_Button {
            get {
                return ResourceManager.GetString("Onboarding_Skip_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} can be used to tweak your eye/face expressions individually..
        /// </summary>
        public static string Onboarding_UI_Calibration_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_Calibration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is used to set up your device, or reset it..
        /// </summary>
        public static string Onboarding_UI_Firmware_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_Firmware_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is everything?.
        /// </summary>
        public static string Onboarding_UI_Header {
            get {
                return ResourceManager.GetString("Onboarding_UI_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is where you can set up your cameras, and {1}..
        /// </summary>
        public static string Onboarding_UI_Home_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_Home_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} shows the status of the app, {1} and other useful information..
        /// </summary>
        public static string Onboarding_UI_Output_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_Output_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is for general app settings, such as {1} and more..
        /// </summary>
        public static string Onboarding_UI_Settings_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_Settings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is used to alter VRChat/VRCFaceTracking specific settings..
        /// </summary>
        public static string Onboarding_UI_VRChat_Description {
            get {
                return ResourceManager.GetString("Onboarding_UI_VRChat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will guide you through setting up the new Babble App..
        /// </summary>
        public static string Onboarding_Welcome_Message {
            get {
                return ResourceManager.GetString("Onboarding_Welcome_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With newer Babbles, you&apos;ll need to perform a first time setup in the Firmware tab (Icon above)..
        /// </summary>
        public static string Onboarding_Wireless_Description1 {
            get {
                return ResourceManager.GetString("Onboarding_Wireless_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It only takes 2 minutes! Select your tracker and mode (wired or wireless). It&apos;s that simple..
        /// </summary>
        public static string Onboarding_Wireless_Description2 {
            get {
                return ResourceManager.GetString("Onboarding_Wireless_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wired or Wireless?.
        /// </summary>
        public static string Onboarding_Wireless_Header {
            get {
                return ResourceManager.GetString("Onboarding_Wireless_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note newer trackers have a 20-second window before they enter camera mode..
        /// </summary>
        public static string Onboarding_Wireless_Note {
            get {
                return ResourceManager.GetString("Onboarding_Wireless_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the log&apos;s output to your clipboard.
        /// </summary>
        public static string Output_CopyButton_Tooltip {
            get {
                return ResourceManager.GetString("Output_CopyButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the logging directory.
        /// </summary>
        public static string Output_OpenLoggingDirectoryButton_Tooltip {
            get {
                return ResourceManager.GetString("Output_OpenLoggingDirectoryButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the log&apos;s output.
        /// </summary>
        public static string Output_SaveButton_Tooltip {
            get {
                return ResourceManager.GetString("Output_SaveButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Title_Header {
            get {
                return ResourceManager.GetString("Output_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Settings.
        /// </summary>
        public static string Settings_Filter_Description {
            get {
                return ResourceManager.GetString("Settings_Filter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn filtering on or off..
        /// </summary>
        public static string Settings_Filter_Enabled_Description {
            get {
                return ResourceManager.GetString("Settings_Filter_Enabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Settings_Filter_Enabled_Label {
            get {
                return ResourceManager.GetString("Settings_Filter_Enabled_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Euro filter settings.
        /// </summary>
        public static string Settings_Filter_Header {
            get {
                return ResourceManager.GetString("Settings_Filter_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how much smoothing is applied to slow movements.
        /// </summary>
        public static string Settings_Filter_MinFreq_Description {
            get {
                return ResourceManager.GetString("Settings_Filter_MinFreq_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum frequency cutoff.
        /// </summary>
        public static string Settings_Filter_MinFreq_Label {
            get {
                return ResourceManager.GetString("Settings_Filter_MinFreq_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how the filter adapts when you move faster.
        /// </summary>
        public static string Settings_Filter_Speed_Description {
            get {
                return ResourceManager.GetString("Settings_Filter_Speed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed coefficient.
        /// </summary>
        public static string Settings_Filter_Speed_Label {
            get {
                return ResourceManager.GetString("Settings_Filter_Speed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High ({0}).
        /// </summary>
        public static string Settings_Filter_Template_High {
            get {
                return ResourceManager.GetString("Settings_Filter_Template_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low ({0}).
        /// </summary>
        public static string Settings_Filter_Template_Low {
            get {
                return ResourceManager.GetString("Settings_Filter_Template_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium ({0}).
        /// </summary>
        public static string Settings_Filter_Template_Medium {
            get {
                return ResourceManager.GetString("Settings_Filter_Template_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from a template.
        /// </summary>
        public static string Settings_Filter_Template_Placeholder {
            get {
                return ResourceManager.GetString("Settings_Filter_Template_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Settings_FirstTime_Button {
            get {
                return ResourceManager.GetString("Settings_FirstTime_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunches the first time setup.
        /// </summary>
        public static string Settings_FirstTime_Description {
            get {
                return ResourceManager.GetString("Settings_FirstTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch first time setup.
        /// </summary>
        public static string Settings_FirstTime_Header {
            get {
                return ResourceManager.GetString("Settings_FirstTime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your GPU to make things run faster! Requires restart.
        /// </summary>
        public static string Settings_GPU_Description {
            get {
                return ResourceManager.GetString("Settings_GPU_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use GPU acceleration.
        /// </summary>
        public static string Settings_GPU_Header {
            get {
                return ResourceManager.GetString("Settings_GPU_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        public static string Settings_Language_Chinese {
            get {
                return ResourceManager.GetString("Settings_Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_Language_Default {
            get {
                return ResourceManager.GetString("Settings_Language_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the app&apos;s language. Switch pages to apply..
        /// </summary>
        public static string Settings_Language_Description {
            get {
                return ResourceManager.GetString("Settings_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language_Header {
            get {
                return ResourceManager.GetString("Settings_Language_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string Settings_Language_Japanese {
            get {
                return ResourceManager.GetString("Settings_Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        public static string Settings_Language_Polish {
            get {
                return ResourceManager.GetString("Settings_Language_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Settings_Language_Spanish {
            get {
                return ResourceManager.GetString("Settings_Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum logging level. Requires restart.
        /// </summary>
        public static string Settings_LogLevel_Description {
            get {
                return ResourceManager.GetString("Settings_LogLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level Verbosity.
        /// </summary>
        public static string Settings_LogLevel_Header {
            get {
                return ResourceManager.GetString("Settings_LogLevel_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where should OSC data be sent?.
        /// </summary>
        public static string Settings_OSC_Description {
            get {
                return ResourceManager.GetString("Settings_OSC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC.
        /// </summary>
        public static string Settings_OSC_Header {
            get {
                return ResourceManager.GetString("Settings_OSC_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string Settings_OSC_IP_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_IP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSC Prefix.
        /// </summary>
        public static string Settings_OSC_Prefix_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_Prefix_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalibrate Address.
        /// </summary>
        public static string Settings_OSC_Recalibrate_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_Recalibrate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Port.
        /// </summary>
        public static string Settings_OSC_ReceivePort_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_ReceivePort_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenter Address.
        /// </summary>
        public static string Settings_OSC_Recenter_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_Recenter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Port.
        /// </summary>
        public static string Settings_OSC_SendPort_Label {
            get {
                return ResourceManager.GetString("Settings_OSC_SendPort_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which app theme to display.
        /// </summary>
        public static string Settings_Theme_Description {
            get {
                return ResourceManager.GetString("Settings_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        public static string Settings_Theme_Header {
            get {
                return ResourceManager.GetString("Settings_Theme_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        public static string Settings_Title_Header {
            get {
                return ResourceManager.GetString("Settings_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the app check for updates on start?.
        /// </summary>
        public static string Settings_Updates_Description {
            get {
                return ResourceManager.GetString("Settings_Updates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string Settings_Updates_Header {
            get {
                return ResourceManager.GetString("Settings_Updates_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send only eye, only face or both? (Change requires VRCFT restart).
        /// </summary>
        public static string VRC_ModuleMode_Description {
            get {
                return ResourceManager.GetString("VRC_ModuleMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set VRCFT module mode.
        /// </summary>
        public static string VRC_ModuleMode_Header {
            get {
                return ResourceManager.GetString("VRC_ModuleMode_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a mode....
        /// </summary>
        public static string VRC_ModuleMode_Placeholder {
            get {
                return ResourceManager.GetString("VRC_ModuleMode_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRChat + VRCFaceTracking Settings.
        /// </summary>
        public static string VRC_Title_Header {
            get {
                return ResourceManager.GetString("VRC_Title_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brings eye tracking to avatars that do not have VRCFaceTracking.
        /// </summary>
        public static string VRC_UseNativeEyeTracking_Description {
            get {
                return ResourceManager.GetString("VRC_UseNativeEyeTracking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Native VRC Eye Tracking.
        /// </summary>
        public static string VRC_UseNativeEyeTracking_Header {
            get {
                return ResourceManager.GetString("VRC_UseNativeEyeTracking_Header", resourceCulture);
            }
        }
    }
}
