//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baballonia.Assets {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Baballonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Settings_Theme_Light_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Light.Content", resourceCulture);
            }
        }

        public static string Settings_Theme_Default_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Default.Content", resourceCulture);
            }
        }

        public static string Settings_Theme_Dark_Content {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark.Content", resourceCulture);
            }
        }

        public static string Shell_Output_Content {
            get {
                return ResourceManager.GetString("Shell_Output.Content", resourceCulture);
            }
        }

        public static string ThemeSettings_Description {
            get {
                return ResourceManager.GetString("ThemeSettings.Description", resourceCulture);
            }
        }

        public static string ThemeSettings_Header {
            get {
                return ResourceManager.GetString("ThemeSettings.Header", resourceCulture);
            }
        }

        public static string OscSettings_Description {
            get {
                return ResourceManager.GetString("OscSettings.Description", resourceCulture);
            }
        }

        public static string OscSettings_Header {
            get {
                return ResourceManager.GetString("OscSettings.Header", resourceCulture);
            }
        }
    }
}
